### ISSUE TITLE
FAQ page for website

### ISSUE THREAD

**Issue by lecy** [UrbanInstitute/nccs#19]
## Selecting an NTEE Code

Nonprofits are required to select an NTEE code when applying for tax-exempt status. As a result, a large number of questions seem to be about how to find the appropriate NTEE code. 

I would suggest starting with this nice summary sheet: 

https://nccs.urban.org/nccs/pubs/ntee-two-page-2005.pdf

Then using category descriptions to get more details on specific categories:

https://nccs.urban.org/nccs/widgets/ntee_tables/ntee_descriptions.html

Highlight the organizational types and how to translate back to the standard NTEE code for the IRS: 

TYPE | Description (original LEV34 code) 
-- | --
AA | Alliance/Advocacy Organizations (*formerly 01*)
MT | Management and Technical Assistance (*formerly 02*)
PA | Professional Societies/Associations (*formerly 03*)
RP | Research Institutes and/or Public Policy Analysis (*formerly 05*)
MS | Monetary Support - Single Organization (*formerly 11*)
MM | Monetary Support - Multiple Organizations (*formerly 12*)
NS | Nonmonetary Support Not Elsewhere Classified (N.E.C.) (*formerly 19*)

## Modifying Your NTEE Code 

We need to be clear it is the IRS, not NCCS, that maintains the official database of codes. 

It is really hard to find accurate information on whether the IRS is actively taking these requests currently. See the new section labeled "Modifying NTEE Codes" and the example response letter from the IRS (I can't even tell from the letter if they made the requested change or not). 

https://nccs.urban.org/nccs/resources/ntee/

It would be helpful for us to create a change form so that we can update records on our end (one version of the NTEE contains edits made by NCCS staff over time, and is more accurate than the official IRS version). 

It would also be helpful to give nonprofits a letter template they can copy and use for the request. I can't find an example, though.

**Comment by Thiyaghessan** [comment]
I think we're going to end up confusing practitioners by asking them to convert NTEEV2 to the original IRS Activity Codes. Users (non-academics) are very unlikely to want to deal with a new taxonomy if it isn't immediately useful to their tax filing needs. 

Should we be maintaining a searchable table of old IRS Activity codes separate from our current NTEEV2 Table for practitioners? I think it would drive more traffic to our site as an information provider and avoid a ton of inevitable emails as users ask how they can translate NTEEV2 codes back to NTEE codes.

**Comment by lecy** [comment]
> Should we be maintaining a searchable table of old IRS Activity codes separate from our current NTEEV2 Table for practitioners?

I agree. Let's use the legacy version as a reference for nonprofits trying to select their NTEE to avoid any confusion: 

https://urbaninstitute.github.io/nccs-legacy/ntee/ntee.html

By default I think we should include NTEE and NTEEV2 in the Core series. 

The metadata table for mission codes would then be something like:  Mission, NTEE, NTEEV2, LEV1, LEV2, LEV3, LEV4, LEV5 and optionally the labels. 

It's mostly jus a tidy version so that each feature is independently selectable to expedite analysis, but NTEEV2 has LEV1-LEV5 info already encoded, which is what makes them much more useful than NTEEV1.

**Comment by Thiyaghessan** [comment]
Hi Jesse,

I'm getting a TOC header rendering for me.

![image](https://github.com/UrbanInstitute/nccs/assets/55271416/d5ec8438-a24c-4b8b-9695-ed4132f05cc4)

**Comment by lecy** [comment]
Yeah, I was hoping kramdown would pick it up automatically. I need to add some gemfiles or just build an HTML version for the page.

**Comment by Thiyaghessan** [comment]
Ok this is helpful to know, I thought it was a rendering error on my part, lets keep this issue open until we resolve it

**Comment by lecy** [comment]
This option works fine: 

https://blog.webjeda.com/jekyll-toc/

See the FAQ layout for implementation: 

https://github.com/UrbanInstitute/nccs/blob/main/_layouts/faq.html

**Making a note to move javascript library to public folder and jQuery import to to head.html**
